version: "3.4"

services:
  php:
    build:
      context: .
      target: symfony_php_debug
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        SKELETON: ${SKELETON:-symfony/skeleton}
        STABILITY: ${STABILITY:-stable}
    image: hub.yohannbiglia.fr/coprosymfony:latest
    restart: unless-stopped
    environment:
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      DATABASE_URL: postgresql://${POSTGRES_USER:-symfony}:${POSTGRES_PASSWORD:-ChangeMe}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-13}
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${MERCURE_URL:-http://mercure:80/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${SERVER_NAME:-http://localhost:3040/.well-known/mercure}
      MERCURE_JWT_SECRET: ${MERCURE_JWT_SECRET:-!ChangeMe!}
    networks:
      - symfony

  nginx:
    image: nginx:alpine
    depends_on:
      - php
    restart: unless-stopped
    volumes:
      - .:/srv/app
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-8000}
    networks:
      - symfony

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_MULTIPLE_DATABASES: app:symfony:ChangeMe,app_test:symfony_test:ChangeMeTest
      
    volumes:
      - ./docker/db/config:/docker-entrypoint-initdb.d:ro
    networks:
      - symfony
    ports:
      - target: 5432
        published: 5432
###< doctrine/doctrine-bundle ###
###> doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    ports:
      - "3040:80"
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
      DEBUG: debug
      MERCURE_EXTRA_DIRECTIVES: |-
        cors_origins *
        anonymous
    networks:
      - symfony
###< symfony/mercure-bundle ###
volumes:
  db-data:

###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
###< doctrine/doctrine-bundle ###
networks:
  symfony:
    name: symfony
