version: "3.4"

# Production environment override
services:
  php:
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}
    build:
      target: symfony_php
    image: hub.yohannbiglia.fr/symfonyphp:prod


  nginx:
    volumes:
      - ./docker/nginx/prod/conf.d:/etc/nginx/conf.d/

  database:
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
